In [3]:
import pickle
import numpy as np

In [4]:
task_file = r"D:\cl\task\test_2024-11-19_1.pickle"

with open(task_file, 'rb') as f:
    task = pickle.load(f)
task

{'start_time': 1732058283.9336996,
 'episode': array([ 1,  1,  1, ..., 12, 12, 12]),
 'step': array([    1,     2,     3, ..., 10456, 10457, 10458]),
 'step_time': array([0.00000000e+00, 5.32944202e-02, 5.52980900e-02, ...,
        1.74554870e+02, 1.74570799e+02, 1.74588071e+02]),
 'state': array([[ -0.86     ,  -6.97     ,   0.       , ...,   0.       ,
           0.       ,   0.       ],
        [  1.2083656,  -4.231875 , 358.38455  , ...,   0.       ,
           0.       ,   0.       ],
        [  1.2120398,  -4.230023 , 358.37878  , ...,   0.       ,
           0.       ,   0.       ],
        ...,
        [ -6.5327377,  -4.798881 ,  58.41415  , ...,   1.       ,
           1.       ,   0.       ],
        [ -6.532514 ,  -4.7989626,  58.414997 , ...,   1.       ,
           1.       ,   0.       ],
        [ -6.5322766,  -4.7991076,  58.416355 , ...,   1.       ,
           1.       ,   0.       ]], dtype=float32),
 'action': array([[[  1.2083655 ,  -4.23187471, 358.38455692,   0. 

In [5]:
task.keys()

dict_keys(['start_time', 'episode', 'step', 'step_time', 'state', 'action', 'reward', 'terminal', 'session_label', 'dlc_read_time', 'dlc_x', 'dlc_y', 'dlc_heading', 'block_labels', 'slit_size', 'trial_slit_depth', 'r_report_box', 'l_report_box', 'start_box', 'cropped_image', 'unity_arena_size', 'camera_rotation', 'mouse_report_delay', 'velocity_threshold', 'start_box_delay', 'distractor', 'target_size', 'grey_screen_active', 'camera_type', 'target_selection', 'distractor_selection', 'occlusion_type', 'target_distance', 'target_rotation', 'reward_size', 'prob_obj_on_left', 'object_on_left', 'reward_episode', 'slit_size_param', 'block_length_param', 'rotate_camera_param', 'epoch_param', 'mouse_report_delay_param', 'prob_block_coherence', 'slit_depth_param', 'target_selection_param', 'distractor_selection_param', 'occlusion_type_param', 'target_spread_param', 'target_rotation_param', 'target_height_param', 'target_distance_param', 'trial_prob_object_left', 'trial_target_spread', 'trial_ta

In [6]:
task['object_on_left']

array([0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0.])

In [8]:
task['reward_episode']

array([ 1,  3,  4,  6, 10, 12])

In [6]:
terminal = task['terminal']
reward = task['reward']

In [7]:
len(reward)

206475

In [8]:
state = task['state']

In [9]:
terminal_index = np.where(terminal)[0]
terminal_index

array([  3031,   5708,   9112,  18767,  20887,  22733,  23911,  27226,
        29038,  29514,  33781,  35587,  36031,  37990,  42073,  44255,
        44853,  45364,  46208,  46984,  48813,  49292,  50105,  51321,
        57024,  58098,  58904,  60371,  61143,  61778,  62686,  63635,
        64320,  64694,  65139,  66233,  68373,  69659,  71008,  74818,
        79913,  80230,  81165,  81720,  82903,  85258,  85780,  86326,
        88039,  89325,  89987,  90670,  91118,  96277,  97521,  98068,
        98527,  98837,  99301,  99663, 102485, 102798, 103224, 103575,
       103842, 104262, 104754, 105125, 105514, 105774, 106076, 110210,
       110930, 111605, 111980, 112404, 112702, 113291, 114351, 116054,
       119221, 120577, 121106, 121686, 122103, 122796, 123363, 124887,
       125874, 126346, 126890, 127256, 127724, 129677, 130926, 131228,
       131571, 131892, 132532, 132915, 133448, 134266, 135203, 136006,
       136586, 136894, 137455, 137701, 138116, 138659, 139258, 139539,
      

In [10]:
np.where(reward == 1)[0]

array([    12,   9166,  20910,  23954,  29567,  33817,  38562,  42127,
        44308,  46265,  47052,  50157,  57062,  58177,  60498,  61207,
        61862,  62807,  63674,  66286,  68424,  71049,  80286,  81215,
        81769,  82947,  86388,  88094,  90048,  90778,  97586,  99013,
        99727, 103897, 105163, 110261, 110980, 111649, 112911, 113339,
       120619, 121170, 123441, 124967, 125919, 127306, 127779, 130080,
       131291, 132585, 133494, 134317, 135258, 136948, 137748, 138170,
       139790, 140330, 140851, 142186, 142865, 143276, 144016, 144534,
       150371, 151520, 152692, 153658, 155501, 156052, 157275, 158163,
       159448, 160432, 161666, 162368, 165168, 168304, 169210, 171142,
       172332, 174946, 178147, 179071, 180082, 180514, 181741, 182240,
       183356, 183824, 186548, 187986, 197120, 198914, 200324, 201202,
       201775, 202992, 204317, 205121, 206357])