In [37]:
import numpy as np 
import matplotlib.pyplot as plt

In [38]:
folder = "C:\\Users\\Windows\\vr4mice_video"

In [39]:
animal_id='CnL15'

In [40]:
# get all files starting with animal_id
import os
files = os.listdir(folder)
files = [f for f in files if f.startswith(animal_id)]

In [41]:
files

['CnL15_2024-06-08_1.pickle',
 'CnL15_2024-06-09_1.pickle',
 'CnL15_2024-06-10_1.pickle',
 'CnL15_2024-06-11_1.pickle',
 'CnL15_2024-06-12_1.pickle',
 'CnL15_2024-06-12_2.pickle',
 'CnL15_2024-06-13_2.pickle',
 'CnL15_2024-06-14_1.pickle',
 'CnL15_2024-06-15_1.pickle',
 'CnL15_2024-06-16_1.pickle',
 'CnL15_2024-06-17_1.pickle',
 'CnL15_2024-06-18_1.pickle',
 'CnL15_2024-06-19_1.pickle',
 'CnL15_2024-06-19_2.pickle']

In [42]:
file = files[-1]

In [43]:
# load the pickle file
import pickle
with open(os.path.join(folder, file), 'rb') as f:
    data = pickle.load(f)
    

In [44]:
data['episode']

array([ 1,  1,  1, ..., 75, 75, 75])

In [45]:
a = data['reward']

In [46]:
a.sum()

71.0

In [47]:
data.keys()

dict_keys(['start_time', 'episode', 'step', 'step_time', 'state', 'action', 'reward', 'terminal', 'cameraSelection', 'target_selection', 'distractor_selection', 'Object_on_Left', 'slitSize', 'slit_depth', 'targetsFromMidline', 'targetsheight', 'mouseReportDelay', 'startBoxDelay', 'velocityThreshold', 'occlusion_type', 'targetsZpos', 'target_rotation', 'L_box_x_min', 'L_box_x_max', 'L_box_z_min', 'L_box_z_max', 'R_box_x_min', 'R_box_x_max', 'R_box_z_min', 'R_box_z_max', 'TT_box_x_min', 'TT_box_x_max', 'TT_box_z_min', 'TT_box_z_max', 'TT_box_angle', 'distractor', 'targetSize', 'Grey_screen_active', 'session_label', 'dlc_read_time', 'dlc_x', 'dlc_y', 'dlc_heading', 'block_labels', 'slit_size', 'trial_slit_depth', 'R_report_box', 'L_report_box', 'start_box', 'cropped_image', 'unity_arena_size', 'camera_roation', 'mouse_report_delay', 'velocity_threshold', 'start_box_delay', 'target_size', 'grey_screen_active', 'camera_type', 'target_distance'])

In [48]:
data['step']

array([     1,      2,      3, ..., 160906, 160907, 160908])

In [49]:
data['step_time']

array([0.00000000e+00, 2.89406776e-02, 8.41968060e-02, ...,
       3.21959613e+03, 3.21961238e+03, 3.21962941e+03])

In [50]:
dt = data['step_time'][1]-data['step_time'][0]

In [51]:
data['step'][-1] * dt

4656.786558151245